### ISSUE TITLE
unable to open file ?

### ISSUE THREAD

**Issue by xltitanlee** [SgtMalicious/FortiOS-Utilities#3]
Hi Team,

I am trying to run the script but it say "FATAL: unable to open file /root/20151030.conf"

here is my commend :

[root@53000-proxy ~]# python --version
Python 2.7.5
[root@53000-proxy ~]# policy_view.py "/root/20151030.conf" dump 1
FATAL: unable to open file /root/T20151030.conf
Loading configuration...

[root@53000-proxy ~]# policy_view.py /root/20151030.conf dump 1
FATAL: unable to open file /root/20151030.conf
Loading configuration...

I am try windows (win 7 x64)  and Linux (centos 6.2 x64) , but it is the same problem 

20151030.conf  is really in the folder and the conf is complete Firewall Config.
Kindly let me know if it needs to be run differently.

Thanks & Regards,

Titan

**Comment by SgtMalicious** [comment]
The script error is pretty generic. Try opening the file directly to see the error message python receives from the operating system: python -c "open('/root/20151030.conf','r')"

**Comment by xltitanlee** [comment]
where is no message when i enter  python -c "open('/root/20151030.conf','r')" in  the operating system

**Comment by SgtMalicious** [comment]
The second argument after the configuration file is either the name of the VDOM you want to look at or <code>none</code>. Is your VDOM named "dump"? Or are you trying to use the dump option for output in CSV format?

**Comment by xltitanlee** [comment]
Hi , Team
I want to use the dump option for output in CSV

**Comment by SgtMalicious** [comment]
You just need to use the proper syntax then. <code>policy_view.py /root/20151030.conf none dump</code> assuming you're not using vdoms, if you're using vdoms replace <code>none</code> with the name of the vdom.
