### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by AngelOfTerror** [SgtMalicious/FortiOS-Utilities#4]
Good afternoon,
Took me some time on the Internet to find a useful script like this. But for some reason, I'm getting errors. I've tried to search on Google for this error, encountered some fixes too ... But I'm afraid I have no idea how to apply them.

```
Y:\Test>fgaddressestocsv.py -i "Y:\Test\sys_config_10.36.25.9.txt" -n
Traceback (most recent call last):
  File "Y:\Test\fgaddressestocsv.py", line 159, in <module>
    main(options, arguments)
  File "Y:\Test\fgaddressestocsv.py", line 145, in main
    results, keys = parse(options.input_file)
  File "Y:\Test\fgaddressestocsv.py", line 77, in parse
    if p_entering_address_block.search(line):

TypeError: cannot use a string pattern on a bytes-like object
```

This is the Python version I'm using;
`Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32`

**Comment by SgtMalicious** [comment]
Wrong repository. The script you're using is here: https://github.com/maaaaz/fgpoliciestocsv

**Comment by AngelOfTerror** [comment]
My apologies! Found two scripts on GitHub, posted the wrong error at the wrong site :(
